// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASBjf8jt37LFtUpQiIBgPCUSHURBCI2W4',
    appId: '1:505927089970:android:9fed50a3fe07377127212b',
    messagingSenderId: '505927089970',
    projectId: 'pi8iftm',
    databaseURL: 'https://pi8iftm-default-rtdb.firebaseio.com',
    storageBucket: 'pi8iftm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIO6_4ScDO7TeuE_HMfHcb3T5A5tLPlk',
    appId: '1:505927089970:ios:04ea59e7a07eac6327212b',
    messagingSenderId: '505927089970',
    projectId: 'pi8iftm',
    databaseURL: 'https://pi8iftm-default-rtdb.firebaseio.com',
    storageBucket: 'pi8iftm.appspot.com',
    androidClientId: '505927089970-ruav90b60u3a1s339ftoebacdgtdlf6m.apps.googleusercontent.com',
    iosClientId: '505927089970-rsvmhbudr8c80j1jn0sic244jju4ldmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.pi8',
  );
}
